### ISSUE TITLE
[REQUEST] Blueberries  

### ISSUE THREAD

**Issue by efffauw** [CanINotUseTruth/Foodables#3]
**Description:**
- Make blueberries be able to be used to make blue dye by putting it in a furnace

**Reason:**
- I think it would add a little bit more substance to the mod, but I actually  made this request because i needed blue dye to make a waystone

**Comment by CanINotUseTruth** [comment]
This is a cool concept may look at working something like this into the mod, the furnace could be a good implementation but I may think of something else.

**Comment by CanINotUseTruth** [comment]
Berries can be ground with the mortar and pestle to make respective coloured dyes, in 1.2.1-1.18.1 which should be out in a few days.
