### ISSUE TITLE
[REQUEST] Deers

### ISSUE THREAD

**Issue by efffauw** [CanINotUseTruth/Foodables#4]
**Description:**
- Add deers to the mod that lives in forests that drop raw venison and can be cooked to make cooked venison raw venison can also be used to make salted venison

**Reason:**
- I think it's cool

sorry if the grammar is a bit messy English is not my first language

**Comment by CanINotUseTruth** [comment]
I have implemented the berries to dye request, it was a good little feature to implement. I am not looking at adding mobs however to my mod at least for the foreseeable future so I will close this issue for now. I appreciate the suggestion however and if you have more now that 1.18 is out please let me know.
